name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TS-Arbitrage-Bot CI Checks
        run: |
          npm ci
          npm run test
          npm run lint
